### ISSUE TITLE
Cos'è un meetup

### ISSUE THREAD

**Issue by Mte90** [WP-Italia-Community/how-to#18]
Fare un documento a riguardo

**Comment by francescamarano** [comment]
Lo vuoi assegnare a me e Giulia Tosato (che non credo sia su GitHub, ma la portiamo?)

**Comment by francescamarano** [comment]
@Mte90 stiamo lavorando con @Glorialchemica a questo https://docs.google.com/document/d/1DjsoEkxcq3b_hpXDqBpZoEBQ40n5SwSDGnMGZGaASGE/edit#
È un documento che c'è già su Rosetta, cosa vuoi mettere qui? Vuoi un testo più lungo su cos'è un Meetup? Vuoi una traduzione dell'handbook?

**Comment by Mte90** [comment]
Direi di metterlo cos→ abbiamo la copia, non si sa mai
