### ISSUE TITLE
Come organizzare un translation day

### ISSUE THREAD

**Issue by Mte90** [WP-Italia-Community/how-to#21]
Convertire questo come articolo https://it.wordpress.org/team/2016/10/28/guida-per-organizzare-un-evento-locale-durante-il-global-wordpress-translation-day/

**Comment by francescamarano** [comment]
I GWTD li organizza il team Polyglots a livello globale, forse noi dovremmo concentrarci su Translation Days locali :-)

**Comment by Mte90** [comment]
duplicato #20
