### ISSUE TITLE
Organizzazione di un wordcamp

### ISSUE THREAD

**Issue by Mte90** [WP-Italia-Community/how-to#22]
https://it.wordpress.org/team/2016/10/27/steal-like-an-artist-wordcamp-edition/

**Comment by francescamarano** [comment]
Lo assegni a me?

**Comment by francescamarano** [comment]
@Mte90 io chiuderei questa issue, è da un lato troppo generica come titolo (un tema immenso, come organizzare un WordCamp) e dall'altra l'articolo citato è molto specifico su come io organizzerei un WordCamp ;-)
Mi sembra che ci siano cose più basic e necessarie. Chiudi? Grazie!
