### ISSUE TITLE
Nuova guida per Slack

### ISSUE THREAD

**Issue by Mte90** [WP-Italia-Community/how-to#35]
Da una discussione su #community risulta che il documento in pdf sia obsoleto e può essere reso più semplice mettendo la parte della comunità internazionale come secondo step e non primo.

# Cosa fare?

Qualcuno che faccia un documento in markdown o html (per via dei link o img) che possiamo caricare qui e poi anche sul portale Rosetta e poi generare il pdf. (Si da html si possono fare i pdf).

Per chi ha difficoltà a fare un documento html faccia il testo e metta delle aree dove vanno messi i link o le img che poi qualcun altro provvederà al resto.

**Comment by simo70** [comment]
Ciao, il documento lo scrivo io. Una precisazione per cortesia: posso iscrivermi allo Slack italiano di WordPress senza passare per quello internazionale?

**Comment by Mte90** [comment]
Si non è obbligatorio quello internazionale è obbligatorio essere registrati su wordpress.org :-)

**Comment by simo70** [comment]
[Slack_per_Wordpress.zip](https://github.com/WP-Italia-Community/how-to/files/1371947/Slack_per_Wordpress.zip)
Ciao, prova a vedere se così è più chiaro. Simona

**Comment by Mte90** [comment]
Perfetto vedo di convertirlo in markdown :-)

**Comment by Mte90** [comment]
eccolo qua https://github.com/WP-Italia-Community/how-to/blob/master/guide/slack.md
Ho tolto le immagini che sono solo loghi (pensavo che fossero degli screen)
