### ISSUE TITLE
Verbali

### ISSUE THREAD

**Issue by francescamarano** [WP-Italia-Community/how-to#47]
Alcuni commenti alla procedura verbali @ #38 
Concordo con tutto quello che è stato scritto da @Mte90 e aggiungo: sarebbe bene dare un formato e una formattazione che aiutino la lettura.

Ad esempio:
- Gli argomenti evidenziati come H2
- Se ci sono delle checklist usare l'apposita funzione (se non erro esiste di default nel tema O2)
- Fare uso di elenchi, titoli e sottotitoli per facilitare lo scorrimento del testo

Rispetto a ODG e Recap nello stesso post, funziona se la persona che fa il recap di prende la briga di postarlo nel canale apposito, se no meglio fare due post diversi.

Sempre usare il formato Standard e non Aside, magari aggiungendo il post come "Nuovo" da bacheca o menu e non da front-end. Per creare Standard da front-end dovete sempre dare un titolo (cliccando su quell'icona illeggbile sulla destra del post. 
<img width="686" alt="screen shot 2018-02-21 at 14 19 37" src="https://user-images.githubusercontent.com/5690173/36482073-525fb724-1712-11e8-8781-dfda2d0ccbd9.png">

Segnare il post come "Da Fare" si colora in rosso, se ci sono dei task per le persone, anche se il blog non serve per gestire i task (potremmo provare a usare GitHub anche per quello, oppure ognuno si organizzi come crede <3 )

**Comment by Mte90** [comment]
Perfetto nella prossima iterazione aggiungo queste cose a meno che non voglia farlo qualcun altro.
