### ISSUE TITLE
Broken Link in sezione Slide

### ISSUE THREAD

**Issue by marcochiesi** [WP-Italia-Community/how-to#56]
Ho notato che i primi 3 link presenti nel file [riferimenti-slide-community.md](../blob/master/slide/riferimenti-slide-community.md) purtroppo non funzionano.
C'è modo di recuperare i link aggiornati?

**Comment by francescamarano** [comment]
Yup, li recupero e metto su al rientro da Londra. Il terzo link ha cambiato username, ma i primi due sono proprio inesistenti.
