### ISSUE TITLE
Rifare la lista meetup

### ISSUE THREAD

**Issue by Mte90** [WP-Italia-Community/how-to#60]
Come da titolo bisogna raccogliere l'elenco dei nuovi meetup e fare una modifica con questi nuovi dati.

**Comment by francescamarano** [comment]
Ma sul sito o qui su GitHub?

**Comment by Mte90** [comment]
qui su github non so se sono aggiornate entrambe o sono diverse.

**Comment by marcochiesi** [comment]
Avevo riallineato io un mesetto fa (Vedi #64 )

**Comment by francescamarano** [comment]
Ho aggiornato su GitHub e su Rosetta
Il problema della lista su GitHub è che non possiamo essere informati su tutti i cambiamenti degli organizzatori locali.
Propongo quindi due cose:
1. Togliere i nomi degli organizzatori e mettere link a canale Slack
2. Su Rosetta, togliere link a Blog (porta ai post taggati con il nome della città, ma è un sistema che non ha più senso visto che non facciamo più annunci per singola città) e mettere link al canale Slack

**Comment by marcochiesi** [comment]
1. Anche secondo me si possono togliere i nomi degli organizzatori. Non è un'informazione particolarmente utile ed è una cosa in più che occorrerebbe tenere aggiornata, oltretutto non si capisce se sia il nome Slack o lo username di WP.org
2. Sul link al Blog, non saprei. Anche se i post per singole città sono rari (ci sono giusto quelli per i nuovi meetup nati), i post mi sembrano taggati correttamente, per cui di fatto il link può essere (un po') utile per ritrovare tutti quei post in maniera rapida anche se sono post "multi-città".
3. Ulteriore proposta: potremmo anche mettere per ciascun meetup i link ad altri punti di presenza online oltre alla pagina di Meetup.com e il canale Slack, tipo sito web, pagina/gruppo Facebook, profilo Twitter, etc. Molti meetup sono attivi anche su altri canali.

In ogni caso direi che la priorità è trovare un format che consenta una semplice sincronizzazione tra GitHub e Rosetta, senza doversi mettere a fare un merge a mano ogni volta. Esempio: si decide che fa fede GitHub e quando si fa un aggiornamento lo si riporta anche su Rosetta, idealmente con un semplice e banale copia-incolla.

**Comment by gAllegr** [comment]
Anche io sono d'accordo per indicare il canale Slack del meetup.
Come link aggiuntivi, concordo sull'inserire anche il link a Meetup, sarebbe utile nel caso di potenziali nuovi contributor che non sono ancora su Slack.
Non concordo invece sull'indicazione delle pagine social, nel tempo potrebbero diventare poco usate o inattive per scarso interesse della comunità locale. Oppure meetup che al momento non hanno determinati profili social potrebbero aggiungerlo in futuro.
In sintesi :) servirebbero controlli periodici

**Comment by Mte90** [comment]
Dobbiamo aiutare i blog ad essere trovati quindi i social fanno la differenza sicuramente rispetto al blog. Poi che non siano usati non possiamo farci molto, se cominciamo a preoccuparci di questo gestire la lista diventa un dramma.
A quel punto potrebbe avere piú senso non mettere il link ai social ma a quello del portale meetup e basta.
Dopotutto si dice sempre ai meetup di iscriversi su slack e cercare il canale e quindi se snelliamo il contenuto della pagina, sarebbe piú facile gestirla.

**Comment by gAllegr** [comment]
I social però sono elencati anche nella pagina Meetup. Scorrendo la pagina, verso la fine c'è "Ci trovi anche su" con i vari link

**Comment by marcochiesi** [comment]
Ok, mi avete convinto. A questo punto direi di tenere la lista più snella possibile in modo da non doversi preoccupare di doverla tenere aggiornata periodicamente, ma solo di aggiungere i nuovi meetup o togliere quelli "estinti" (cosa che immagino sarà fatta da @francescamarano o da altri eventuali nuovi deputy italiani).

Rimane da decidere che formato usare per la lista, in modo che poi sia sufficiente fare un copia-incolla da una piattaforma all'altra.
Su [Github](https://github.com/WP-Italia-Community/how-to/blob/master/meetup/organizzatori.md) c'è un elenco numerato con il solo link a Meetup.com messo sul nome della città, mentre su [Rosetta](https://it.wordpress.org/meetup/) ogni città è in un `<h2>` con sotto i link.

Per il link al canale slack io metterei anche il nome del canale come testo del link, e non semplicemente "Slack", in quanto il link funziona solo via web, ma per chi usa la app di Slack è più comodo raggiungere il canale in base al nome (che non si desume dall'URL).

Last but not least, a questo punto probabilmente conviene anche rinominare il file che attualmente si chiama `organizzatori.md`, nome che non avrà più senso togliendo gli organizzatori.

**Comment by Mte90** [comment]
Ho cambiato il titolo del ticket che ora si occupa di riscrivere l'elenco secondo quanto detto:

- Togliere i nomi degli organizzatori
- Rinominare il file in elenco.md (ad oggi si chiama organizzatori.md)
- Riferimento al canale slack di ogni meetup

**Comment by francescamarano** [comment]
Fatto
