### ISSUE TITLE
Cancellare il file Codice di Condotta da Regole della Community

### ISSUE THREAD

**Issue by francescamarano** [WP-Italia-Community/how-to#70]
@Mte90, @TheDarkMist ha aggiornato il codice di condotta dei WordCamp e io l'ho caricato nella cartella "Testi Siti WordCamp" - evitiamo i doppioni, please cancella il tuo.
Le regole della community sono diverse dal Codice di Condotta ;-)
Grazie mille!

**Comment by Mte90** [comment]
A meno che qualcuno voglia farlo per hacktoberfest, fate una pr altrimenti con calma nei prossimi giorni lo rimuovo io :-)

**Comment by lloc** [comment]
Done
