### ISSUE TITLE
Come gestire un harassment report

### ISSUE THREAD

**Issue by francescamarano** [WP-Italia-Community/how-to#80]
Esiste un file gestione-report-coc.md 
Non sono sicura che il posto giusto sia https://github.com/WP-Italia-Community/how-to/blob/master/regole-della-comunita/gestione-report-coc.md

Al momento il CoC si applica i WordCamp e per quanto riguarda i Meetup c'è una procedura simile ma non così codificata.
Si accettanno consigli :)

**Comment by Mte90** [comment]
migrato a https://trello.com/c/YE38A0pi/14-creazione-glossario-termin-del-team-community
